[build]
  functions="functions"
  publish="public"
  command="yarn build"

# [dev] # https://github.com/netlify/netlify-dev-plugin#project-detection
#   command = "next start" # Command to start your dev server
#   port = 3000 # Port that the dev server will be listening on
#   publish = "public" # Folder with the static content for _redirect file


# # ## more info https://www.netlify.com/docs/netlify-toml-reference/
